name = "saturn-replies-inbound"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "saturn-social"
database_id = "2cc8bddd-d422-4d1e-8480-c1c75c8d02b0"

[[send_email]]
name = "NOTIFY"
destination_address = "daniel@danieldaum.net"
